[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["cd aurora_backend && pip install -r ../requirements.txt"]

[phases.build]
cmds = ["cd aurora_backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd aurora_backend && python manage.py migrate --noinput && gunicorn aurora_backend.wsgi:application --bind 0.0.0.0:$PORT"

